# Topic: *Pandas*

**Pandas ?**
- Pandas is a Python library used for working with data sets.

- It has functions for analyzing, cleaning, exploring, and manipulating data.

- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

- Data analysis requires lots of processing, such as restructuring, cleaning or merging, etc. There are different tools are   
  available for fast data processing, such as Numpy, Scipy, Cython, and Panda. But we prefer Pandas because working with Pandas is fast, simple and more expressive than other tools.

- Pandas is built on top of the Numpy package, means Numpy is required for operating the Pandas.

Series: series is a data structure in pandas that hold an array  of information along with named index

- formal defination: one-dimensional ndarray with axis labels

In [13]:
import numpy as np
import pandas as pd

- Numpy array has numeric index

- pandas series add on a labeled index

Label Index

In [14]:
myindex = ['USA', 'Canada', 'Mexico'] # custom index for the series
mydata = [1776, 1867, 1821] # data for the series

In [15]:
myser = pd.Series(index=myindex, data=mydata) # creating a pandas series
print(myser)

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [16]:
type(myser) # to check the type of the series

pandas.core.series.Series

In [17]:
myser['Canada'] # accessing data using custom index

np.int64(1867)

In [18]:
myser[0] # accessing data using default numeric index

C:\Users\admin\AppData\Local\Temp\ipykernel_32480\3672126530.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  myser[0] # accessing data using default numeric index

np.int64(1776)

In [19]:
ages = {'John': 5, 'Alice': 10, 'Bob': 7}  # dictionary of ages
age_series = pd.Series(ages) # creating a pandas series from the dictionary
print(age_series) # printing the series

John      5
Alice    10
Bob       7
dtype: int64

In [20]:
#exercise

#TASK: Use pandas to grab the expenses paid by Bob.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
#  Link to Solution: https://gist.github.com/Pierian-Data/3d7f7cb3528f015d9584d04a7168b97f

expenses = pd.Series({'Andrew':200,'Bob':150,'Claire':450})

bob_expenses =expenses["Bob"]
# bob_expense = # Use pandas, don't just manually write in the number here.expensesexpenses
print("bob_expense: ", bob_expenses)

bob_expense:  150

In [21]:
#imaginary Sales Data for 1st and 2nd quarter for global company
q1 = pd.Series({'Japan':80,'China':450,'India':200, 'USA':250})
q2 = pd.Series({'Brazil':100,'China':500,'India':200,'USA':260})

In [22]:
sales_Q1 =pd.Series(q1) # creating series for sales in Q1
sales_Q2 =pd.Series(q2) # creating series for sales in Q2

In [23]:
sales_Q1 #  viewing sales in Q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [24]:
sales_Q2 # viewing sales in Q2

Brazil    100
China     500
India     200
USA       260
dtype: int64

In [25]:
sales_Q1["Japan"] # accessing sales data for Japan in Q1

np.int64(80)

In [26]:
sales_Q1[0] # accessing sales data for Japan in Q1 using default numeric index

C:\Users\admin\AppData\Local\Temp\ipykernel_32480\3680541565.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_Q1[0] # accessing sales data for Japan in Q1 using default numeric index

np.int64(80)

In [27]:
sales_Q1.keys() # viewing all the keys (countries) in sales_Q1

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [28]:
sales_Q1.values # viewing all the sales values in sales_Q1

array([ 80, 450, 200, 250])

In [29]:
list = [1,2] * 2 # list replication
expected_output = np.array([1,2]) * 2 # numpy array replication
expected_output

array([2, 4])

In [30]:
#similiarly we can perform arithmetic operations on pandas series
sales_Q1 * 2 # multiplying all sales values in Q1 by 2

Japan    160
China    900
India    400
USA      500
dtype: int64

In [31]:
sales_Q1/1000 # converting sales values in Q1 from units to thousands

Japan    0.08
China    0.45
India    0.20
USA      0.25
dtype: float64

In [32]:
sales_Q1 + sales_Q2 # adding sales data for Q1 and Q2, aligning by index

Brazil      NaN
China     950.0
India     400.0
Japan       NaN
USA       510.0
dtype: float64

In [33]:
sales_Q1.add(sales_Q2, fill_value=0) # adding sales data for Q1 and Q2, filling missing values with 0

Brazil    100.0
China     950.0
India     400.0
Japan      80.0
USA       510.0
dtype: float64

DataFrame: is a table with rows and column that can be easily restructure and filtered

- formal defination: a group of pandas series object that share the same index

In [34]:
import numpy as np
import pandas as pd

In [35]:
np.random.seed(101)  # for reproducibility
mydata = np.random.randint(0,101,(4,3)) # generating random integers between 0 and 100 in a 4x3 array
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [36]:
myindex = ['USA', 'Canada', 'Mexico',"India"] # custom index for the rows
mycolumns = ['Jan', 'Feb', 'Mar'] # custom index for the columns
df = pd.DataFrame(data = mydata, index = myindex, columns = mycolumns) # creating a pandas DataFrame
df # viewing the DataFrame

        Jan  Feb  Mar
USA      95   11   81
Canada   70   63   87
Mexico   75    9   77
India    40    4   63

In [37]:
df.info() # getting information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, USA to India
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

Basic Properties

In [38]:
pwd # checking current working directory

'c:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\notebooks'

In [39]:
ls # listing files in the current directory

 Volume in drive C has no label.
 Volume Serial Number is 5492-6106

 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks


 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks


 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks


 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks


 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks


 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks


 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks

File Not Found

In [40]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\tips.csv") # reading a CSV file into a DataFrame
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

reading the Dataframe information

In [41]:
df.columns # viewing the column names of the DataFrame

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [42]:
df.index # viewing the index of the DataFrame

RangeIndex(start=0, stop=244, step=1)

In [43]:
df.head(2) # viewing the first few rows of the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [44]:
df.tail(2) # viewing the last few rows of the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [45]:
df.info() # getting information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [46]:
df.describe() # getting statistical summary of numerical columns in the DataFrame

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [47]:
df.describe().transpose() # transposing the statistical summary for better readability

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

retrieving the information from the dataframe:  Information based on Columns

In [48]:
df.head() # viewing the first few rows of the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

Grabbing columns

In [49]:
df['total_bill'] # accessing the 'total_bill' column of the DataFrame

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [50]:
mylist = ['total_bill', 'tip'] # list of columns to access
df[mylist] # accessing multiple columns using the list

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [51]:
df[['total_bill','tip']] # accessing multiple columns directly by specifying a list of column names

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

Adding Columns

In [52]:
df['tip'] + df["total_bill"] # adding values from 'tip' and 'total_bill' columns

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [53]:
df['tip_percentage'] = 100 * df['tip']/df['total_bill'] # calculating tip as a percentage of total bill
np.round(df['tip_percentage'],2)

0       5.94
1      16.05
2      16.66
3      13.98
4      14.68
       ...
239    20.39
240     7.36
241     8.82
242     9.82
243    15.97
Name: tip_percentage, Length: 244, dtype: float64

In [54]:
df.head() # to view the updated DataFrame with the new 'tip_percentage' column

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765

In [55]:
df['price_per_person'] = df['total_bill'] / df['size'] # calculating price per person by dividing total bill by size of the party
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4832732618637221,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5296068606052842,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3506806155565404,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6011891618747196,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3511451626698139,Thur672,15.974441

In [56]:
df['price_per_person'] = np.round(df['total_bill'] / df['size'],2) # calculating price per person by dividing total bill by size of the party
df.head() # viewing the updated DataFrame with the new 'price_per_person' column

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765

removing columns

In [57]:
df.drop('tip_percentage', axis =1 , inplace=True) # removing the 'tip_percentage' column from the DataFrame
df.head() # viewing the DataFrame after removing the 'tip_percentage' column
df.info() # getting information about the DataFrame after removing the column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [58]:
df.shape # getting the shape of the DataFrame (rows, columns)

(244, 11)

In [59]:
df.shape[0] # getting the number of rows in the DataFrame

244

In [60]:
df.shape[1] # getting the number of columns in the DataFrame

11

retrieving the information from the dataframe:  Information based on Rows

- index: index to be unique for every row

In [61]:
df.index # getting the index of the DataFrame

RangeIndex(start=0, stop=244, step=1)

In [62]:
df = df.set_index("Payment ID") # setting the 'Payment_ID' column as the index
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

Grabbing rows

In [63]:
df.iloc[0] # accessing the first row of the DataFrame using integer-location based indexing

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [64]:
df.loc['Sun2959'] # accessing the row with index label 'Sun2959' using label-based indexing

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

Grabbing multiple rows

In [65]:
df.iloc[0: 4] # accessing rows from index 0 to 4 using label-based indexing

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994

In [66]:
df.loc[['Sun2959','Sun4608']] # accessing multiple rows using their index labels

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

removing the rows

In [67]:
df.drop('Sun2959', axis = 0) # removing the row with index label 'Sun2959' from the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [68]:
new_one = df.iloc[0] # creating a new DataFrame with the first 6 rows of the original DataFrame
new_one

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

conditional filtering: filter by single condition

In [69]:
myindex = ['USA','CANADA','MEXICO'] # custom index for the series
Year = [1776,1867,1821] # data for the series
POP = [328,38,126] # population data for the series
GDP = [20.5,1.7,1.22] # GDP data for the series

df = pd.DataFrame({'Year': Year,
                   'Pop': POP,
                   'GDP': GDP}, index=myindex) # creating a DataFrame with multiple columns
df # viewing the DataFrame

        Year  Pop    GDP
USA     1776  328  20.50
CANADA  1867   38   1.70
MEXICO  1821  126   1.22

In [70]:
df['Pop'] > 50 # boolean indexing to check which populations are greater than 50

USA        True
CANADA    False
MEXICO     True
Name: Pop, dtype: bool

In [71]:
df[df['Pop'] > 50] # filtering the DataFrame to show only rows where population is greater than 50

        Year  Pop    GDP
USA     1776  328  20.50
MEXICO  1821  126   1.22

conditional filtering: filter by multiple condition

In [72]:
import pandas as pd
import numpy as np

In [73]:
df = pd.read_csv('C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [74]:
df['total_bill'] # checking which total bills are greater than 50

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [75]:
df[df['total_bill']> 40] # filtering the DataFrame to show only rows where total bill is greater than 40

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [76]:
df[df['sex'] == 'Male'] # filtering the DataFrame to show only rows where sex is 'Male'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [77]:
df[df['size'] > 3] # filtering the DataFrame to show only rows where size is greater than 3

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
13,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6011163105616890,Sun2971
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,30502930499388,Sat907
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,630415546013,Sat4947
33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,377742985258914,Sat6649
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
54,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6569607991983380,Sun9470
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
63,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,Chad Hart,580171498976,Sat4178
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,30344778738589,Thur4924
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4689079711213722,Sun22
119,24.08,2.92,Female,No,Thur,Lunch,4,6.02,Melanie Jordan,676212062720,Thur8063
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,503857080488,Thur3948
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179
153,24.55,2.00,Male,No,Sun,Dinner,4,6.14,Todd Patterson,4416804908942159,Sun8670
154,19.77,2.00,Male,No,Sun,Dinner,4,4.94,James Smith,213169731428229,Sun5814
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
157,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,213158685144262,Sun7015
159,16.49,2.00,Male,No,Sun,Dinner,4,4.12,Christopher Soto,30501814271434,Sun1781
160,21.50,3.50,Male,No,Sun,Dinner,4,5.38,Travis Gonzalez,3527668419764685,Sun245
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059
185,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,30362407455623,Sun5842
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
204,20.53,4.00,Male,Yes,Thur,Lunch,4,5.13,Scott Kim,3570611756827620,Thur2160
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,Sat6735
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4590982568244,Sat7320
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863
227,20.45,3.00,Male,No,Sat,Dinner,4,5.11,Robert Bradley,213141668145910,Sat4319
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4258682154026,Sat7872

In [78]:
#AND (&) operator -- Both condition need to be true
#OR (|) operator  --either condition need to be true
#Not (~) operator --negate the condition

In [79]:
df[(df['total_bill'] > 30) & (df['sex'] =='Male')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6011525851069856,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5356177501009133,Thur8801
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,370307040837149,Sun5109
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,346656312114848,Sun9851
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,30184049218122,Sat8361
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929

In [80]:
df[(df['day']== 'Sun') | (df['day']=='Sat') | (df['day']== 'Fri')] # filtering the DataFrame to show only rows where day is 'Sun', 'Sat', or 'Fri'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [81]:
option = ['Sat', 'Sun', 'Fri']
df[df['day'].isin(option)] # checking which days are in the specified list

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

Apply (.apply()) on single column

In [82]:
import pandas as pd
import numpy as np

In [83]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\tips.csv") # reading a CSV file into a DataFrame
df.head() # viewing the first few rows of the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [84]:
def last_four(num):   # function to get the last four digits of a number
    return str(num)[-4:]

In [85]:
last_four(1234567890) # testing the last_four function with a sample number

'7890'

In [86]:
df['CC Number'].apply(last_four) # applying the last_four function to the 'CC Number' column to get the last four digits

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [87]:
df["last_four"] = df['CC Number'].apply(last_four) # creating a new column in the DataFrame with the last four digits of the 'CC Number'
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221

In [88]:
df.drop(['mns]'], axis = 1).head()

KeyError: "['mns]'] not found in axis"

In [ ]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
def bill(price):
    if price < 10:
        return '$'
    elif price >= 10 and price < 30:
        return '$$'
    else:
        return "$$$"

In [ ]:
df['bill'] =  df['total_bill'].apply(bill) # creating a new column 'bill' by applying the bill function to 'total_bill' 
df['bill']

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: bill, Length: 244, dtype: object

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,mns],last_four,bill
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,9230,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,1322,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,5994,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,7221,$$

Apply (.apply()) on multiple column

In [ ]:
def simple(num): # function to double the input number
    return num*2

In [ ]:
simple(2) # testing the simple function with a sample number

4

In [ ]:
lambda num: num*2 # lambda function to double the input number

In [ ]:
df['total_bill'].apply(simple) # applying the simple function to double the values in the 'total_bill' column

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df['total_bill'].apply(lambda num: num*2) # applying the lambda function to double the values in the 'total_bill' column

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [ ]:
def quality(total_bill,tip):  # function to classify tip generosity
    if tip/total_bill > 0.25:
        return 'Generous'
    else: 
        return 'Other'

In [ ]:
quality(16.99,1.01)

'Other'

In [ ]:
df['Quality'] = df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']), axis=1) # applying the quality function row-wise to classify tip generosity
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Quality
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Other
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Other
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,Other
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Other
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,Other

In [ ]:
df['Quality'] = np.vectorize(quality)(df['total_bill'],df['tip']) # applying the quality function using np.vectorize for better performance
df['Quality']

0      Other
1      Other
2      Other
3      Other
4      Other
       ...
239    Other
240    Other
241    Other
242    Other
243    Other
Name: Quality, Length: 244, dtype: object

In [ ]:
df.head() # viewing the first few rows of the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Quality
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Other
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Other
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,Other
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Other
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,Other

In [ ]:
import timeit

Statistical Information & Sorting: Describing and Sorting

In [ ]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\tips.csv") # reading a CSV file into a DataFrame

In [ ]:
df.head() # viewing the first few rows of the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.describe().transpose() # getting statistical summary of numerical columns in the DataFrame

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [ ]:
df.sort_values('tip', ascending=False) # sorting the DataFrame by 'tips' column in descending order

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
...,...,...,...,...,...,...,...,...,...,...,...
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032

In [ ]:
#sorting by multiple columns
df.sort_values(['tip','total_bill'], ascending=[False,True]) # sorting by 'tip' in descending order and 'total_bill' in ascending order

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
...,...,...,...,...,...,...,...,...,...,...,...
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032

In [ ]:
#grab index location of #min & #max values in 'tip' column

In [ ]:
df['total_bill'].max() # getting the maximum value in the 'total_bill' column

np.float64(50.81)

In [ ]:
df['total_bill'].idxmax() # getting the index label of the row with the maximum value in the 'total_bill' column

170

In [ ]:
df['total_bill'].idxmin() # getting the index label of the row with the minimum value in the 'total_bill' column

67

In [ ]:
df.iloc[df['total_bill'].idxmax()] # accessing the row with the maximum value in the 'total_bill' column using iloc

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
Name: 170, dtype: object

In [ ]:
df.iloc[170] # accessing the row at index position 170 using iloc

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
Name: 170, dtype: object

In [ ]:
numeric_df = df.select_dtypes(include=np.number)
display(numeric_df.corr().transpose())
 # calculating the correlation matrix for numerical columns in the DataFrame

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [ ]:
df['sex'].value_counts() # counting the occurrences of each unique value

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
df['day'] # accessing the 'day' column of the DataFrame

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object

In [ ]:
df['day'].unique() # getting unique values in the 'days' column

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [ ]:
df['day'].nunique() # getting the number of unique values in the 'day' column

4

In [ ]:
# replacing multiple values in a column

df['sex'].replace(['Female','Male'],['F','M'])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [ ]:
mymap = {'Female': 'F',"Male": 'M'} # creating a mapping dictionary for replacement

In [ ]:
df['sex'].map(mymap)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [ ]:
df.duplicated() # checking for duplicate rows in the DataFrame

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [ ]:
# just to show comaprison of the duplicate function
simple_df = pd.DataFrame([1,2,2,2],['a','b','c','d'])
simple_df

   0
a  1
b  2
c  2
d  2

In [ ]:
simple_df.duplicated() #finding duplicate rows in the simple_df DataFrame

a    False
b    False
c     True
d     True
dtype: bool

In [ ]:
simple_df.drop_duplicates() # removing duplicate rows from the simple_df DataFrame

   0
a  1
b  2

In [ ]:
df[df['total_bill'].between(10,20, inclusive='both')] # checking which total bill values are between 10 and 20 alon with inclusivityg the boundaries

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219,Sun2546
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930,Sat7220
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
#Grab the number nlargest and nsmallest values
df.nlargest(3,'total_bill') # getting the 3 largest values in the 'total_bill' column

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139

In [ ]:
df.sort_values('tip',ascending=False).iloc[0:2]  # getting the 2 smallest values in the 'tip' column

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.0,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.0,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [ ]:
df.nsmallest(2,'tip') # getting the 2 smallest values in the 'tip' column

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.0,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
92,5.75,1.0,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780

In [ ]:
df.sort_values('tip',ascending=True).iloc[0:2] # getting the 2 smallest values in the 'tip' column using iloc

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
92,5.75,1.0,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.0,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801

In [ ]:
#calling of five or nth number row : using random sampling
df.sample(4) # randomly sampling 5 rows from the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
63,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,Chad Hart,580171498976,Sat4178
227,20.45,3.00,Male,No,Sat,Dinner,4,5.11,Robert Bradley,213141668145910,Sat4319
82,10.07,1.83,Female,No,Thur,Lunch,1,10.07,Julie Moody,630413282843,Thur4909
218,7.74,1.44,Male,Yes,Sat,Dinner,2,3.87,Nicholas Archer,340517153733524,Sat4772

In [ ]:
df.sample(frac=0.1) # randomly sampling 10% of the rows from the DataFrame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3544447755679420,Sat8549
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4689079711213722,Sun22
131,20.27,2.83,Female,No,Thur,Lunch,2,10.14,Ashley Burke,5394652998970066,Thur9005
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4258682154026,Sat7872
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4427601595688633,Sat4056
124,12.48,2.52,Female,No,Thur,Lunch,2,6.24,Jordan Diaz,4472778228206399,Thur208
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
46,22.23,5.00,Male,No,Sun,Dinner,2,11.12,Joshua Gilmore,4292072734899,Sun7097
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4387671121369212,Sun3279
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5448125351489749,Sat9618
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,Jessica Ibarra,4999759463713,Sun4474
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
136,10.33,2.00,Female,No,Thur,Lunch,2,5.16,Donna Kelly,180048553626376,Thur1393
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5181236182893396,Fri6963
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
130,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,213113680829581,Thur1446
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,Troy Guerrero,3560782621035582,Sat6683
163,13.81,2.00,Male,No,Sun,Dinner,2,6.90,Charles Newton,5552793481414044,Sun8594
146,18.64,1.36,Female,No,Thur,Lunch,3,6.21,Kelly Estrada,60463302327,Thur3941
195,7.56,1.44,Male,No,Thur,Lunch,2,3.78,Michael White,4865390263095532,Thur697
120,11.69,2.31,Male,No,Thur,Lunch,2,5.84,Kenneth Goodman,4891259691010,Thur8289
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5161695527390786,Sat6406

Missing Data: when reading in missing value, pandas will display them as NAN values

- Keep it
- Remove it
- Replace it

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.nan # representing missing data with NaN (Not a Number)

nan

In [ ]:
pd.NA # pandas' own missing value representation

In [ ]:
pd.NaT # Not a Time (used for missing datetime values)

NaT

In [ ]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\movie_scores.csv") # reading a CSV file into a DataFrame

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
df.shape # getting the shape of the DataFrame (rows, columns)

(5, 6)

In [ ]:
df.isnull() # checking for missing values in the DataFrame

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
df.notnull() # checking for non-missing values in the DataFrame

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [ ]:
df[df['pre_movie_score'].notnull()] # checking for non-missing values in the 'pre_movie_score' column

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df[(df['pre_movie_score'].isnull()) & (df['first_name'].notnull())] # checking for missing values in the 'pre_movie_score' column

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [ ]:
df #keep data

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
#drop data
help(df.dropna) # getting help on the dropna function

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [ ]:
df.dropna() # dropping rows with any missing values from the DataFrame

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df.dropna(thresh =1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df.dropna(axis =1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
df.dropna(subset=['pre_movie_score','last_name']) # dropping rows with missing values in the 'pre_movie_score' column

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
help(df.fillna) # getting help on the fillna function

Help on method fillna in module pandas.core.generic:

fillna(
    value: 'Hashable | Mapping | Series | DataFrame | None' = None,
    *,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool_t' = False,
    limit: 'int | None' = None,
    downcast: 'dict | None | lib.NoDefault' = <no_default>
) -> 'Self | None' method of pandas.core.frame.DataFrame instance
    Fill NA/NaN values using the specified method.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    method : {'backfill', 'bfill', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series:

        * ffill: propagate last valid observation forward to next valid.
        * backfill / bfill: use next valid observation to fill gap.

        .. deprecated:: 2.1.0
            Use ffill or bfill instead.

    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        If method is specified, this is the maximum number of consecutive
        NaN values to forward/backward fill. In other words, if there is
        a gap with more than this number of consecutive NaNs, it will only
        be partially filled. If method is not specified, this is the
        maximum number of entries along the entire axis where NaNs will be
        filled. Must be greater than 0 if not None.
    downcast : dict, default is None
        A dict of item->dtype of what to downcast if possible,
        or the string 'infer' which will try to downcast to an appropriate
        equal type (e.g. float64 to int64 if possible).

        .. deprecated:: 2.2.0

    Returns
    -------
    Series/DataFrame or None
        Object with missing values filled or None if ``inplace=True``.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Examples
    --------
    >>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
    ...                    [3, 4, np.nan, 1],
    ...                    [np.nan, np.nan, np.nan, np.nan],
    ...                    [np.nan, 3, np.nan, 4]],
    ...                   columns=list("ABCD"))
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [ ]:
#fill data
df['pre_movie_score'].fillna(0) # filling missing values in the 'pre_movie_score' column with 0

0    8.0
1    0.0
2    0.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [ ]:
df['pre_movie_score'].mean() # calculating the mean of the 'pre_movie_score' column

np.float64(7.0)

In [ ]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean()) # filling missing values in the 'pre_movie_score' column with the mean of that column

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [ ]:
# Fill numeric columns with their column means, then fill text columns with a placeholder
df = df.fillna(df.mean(numeric_only =True)).fillna({
	'first_name': 'Unknown',
	'last_name': 'Unknown',
	'sex': 'Unknown'
})
df

  first_name last_name    age      sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00        m              8.0              10.0
1    Unknown   Unknown  52.75  Unknown              7.0               9.0
2       Hugh   Jackman  51.00        m              7.0               9.0
3      Oprah   Winfrey  66.00        f              6.0               8.0
4       Emma     Stone  31.00        f              7.0               9.0

In [ ]:
air_ticket = {'first': 100, 'last': 50, 'sex': np.nan, 'age': 30}
df = pd.Series(air_ticket) # creating a pandas Series from the air_ticket dictionary
df

first    100.0
last      50.0
sex        NaN
age       30.0
dtype: float64

In [ ]:
df.interpolate() # filling missing values using interpolation (near by boundary limit values)

first    100.0
last      50.0
sex       40.0
age       30.0
dtype: float64

Groupby Operation

In [ ]:
import pandas as pd 
import numpy as np

In [105]:
#mass per gallon dataset
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\mpg.csv") # reading a CSV file into a DataFrame
df.head() # viewing the first few rows of the DataFrame

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [ ]:
df.columns # viewing the column names of the DataFrame

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
df['model_year'].unique() # getting unique values in the 'model_year' column

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [ ]:
df['model_year'].value_counts() # counting occurrences of each unique value in the 'model_year' column

model_year
73    40
78    36
76    34
82    31
75    30
80    29
79    29
81    29
70    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

#error handling in groupby function

In [106]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [ ]:
df.groupby('model_year').describe().transpose() # getting statistical summary of numerical columns grouped by 'model_year'

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000
origin       count    29.000000    28.000000    28.000000    40.000000
             mean      1.310345     1.428571     1.535714     1.375000
             std       0.603765     0.741798     0.792658     0.667467
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       1.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000
origin       count    27.000000    30.000000    34.000000    28.000000
             mean      1.666667     1.466667     1.470588     1.571429
             std       0.832050     0.730297     0.706476     0.835711
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       2.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000
origin       count    36.000000    29.000000    29.000000    29.000000
             mean      1.611111     1.275862     2.206897     1.965517
             std       0.837608     0.591400     0.818505     0.944259
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     2.000000     1.000000
             50%       1.000000     1.000000     2.000000     2.000000
             75%       2.000000     1.000000     3.000000     3.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000
origin       count    31.000000
             mean      1.645161
             std       0.914636
             min       1.000000
             25%       1.000000
             50%       1.000000
             75%       3.000000
             max       3.000000

In [ ]:
df.groupby(['model_year', 'cylinders']).mean(numeric_only=True) # calculating the mean of numerical columns grouped by 'model_year' and 'cylinders'

                            mpg  displacement  horsepower       weight  \
model_year cylinders
70         4          25.285714    107.000000   87.714286  2292.571429
           6          20.500000    199.000000   91.750000  2710.500000
           8          14.111111    367.555556  183.666667  3940.055556
71         4          27.461538    101.846154   77.583333  2056.384615
           6          18.000000    243.375000   98.875000  3171.875000
           8          13.428571    371.714286  166.857143  4537.714286
72         3          19.000000     70.000000   97.000000  2330.000000
           4          23.428571    111.535714   85.142857  2382.642857
           8          13.615385    344.846154  159.692308  4228.384615
73         3          18.000000     70.000000   90.000000  2124.000000
           4          22.727273    109.272727   82.909091  2338.090909
           6          19.000000    212.250000  102.125000  2917.125000
           8          13.200000    365.250000  170.000000  4279.050000
74         4          27.800000     96.533333   74.000000  2151.466667
           6          17.857143    230.428571  101.666667  3320.000000
           8          14.200000    315.200000  146.000000  4438.400000
75         4          25.250000    114.833333   84.916667  2489.250000
           6          17.583333    233.750000   96.750000  3398.333333
           8          15.666667    330.500000  142.000000  4108.833333
76         4          26.766667    106.333333   75.600000  2306.600000
           6          20.000000    221.400000   98.700000  3349.600000
           8          14.666667    324.000000  146.333333  4064.666667
77         3          21.500000     80.000000  110.000000  2720.000000
           4          29.107143    106.500000   78.785714  2205.071429
           6          19.500000    220.400000  102.000000  3383.000000
           8          16.000000    335.750000  152.375000  4177.500000
78         4          29.576471    112.117647   79.705882  2296.764706
           5          20.300000    131.000000  103.000000  2830.000000
           6          19.066667    213.250000  109.833333  3314.166667
           8          19.050000    300.833333  135.500000  3563.333333
79         4          31.525000    113.583333   75.750000  2357.583333
           5          25.400000    183.000000   77.000000  3530.000000
           6          22.950000    205.666667  105.000000  3025.833333
           8          18.630000    321.400000  131.900000  3862.900000
80         3          23.700000     70.000000  100.000000  2420.000000
           4          34.612000    111.000000   74.043478  2360.080000
           5          36.400000    121.000000   67.000000  2950.000000
           6          25.900000    196.500000  111.000000  3145.500000
81         4          32.814286    108.857143   72.950000  2275.476190
           6          23.428571    184.000000  100.714286  3093.571429
           8          26.600000    350.000000  105.000000  3725.000000
82         4          32.071429    118.571429   79.148148  2402.321429
           6          28.333333    225.000000  102.333333  2931.666667

                      acceleration    origin
model_year cylinders
70         4             16.000000  2.285714
           6             15.500000  1.000000
           8             11.194444  1.000000
71         4             16.961538  1.923077
           6             14.750000  1.000000
           8             12.214286  1.000000
72         3             13.500000  3.000000
           4             17.214286  1.928571
           8             13.000000  1.000000
73         3             13.500000  3.000000
           4             17.136364  2.000000
           6             15.687500  1.250000
           8             12.250000  1.000000
74         4             16.400000  2.200000
           6             16.857143  1.000000
           8             14.700000  1.000000
75         4             15.833333  2.166667
           6             17.708333  1.000000
           8             13.166667  1.000000
76         4             16.866667  1.866667
           6             17.000000  1.300000
           8             13.222222  1.000000
77         3             13.500000  3.000000
           4             16.064286  1.857143
           6             16.900000  1.400000
           8             13.662500  1.000000
78         4             16.282353  2.117647
           5             15.900000  2.000000
           6             16.391667  1.166667
           8             13.266667  1.000000
79         4             15.991667  1.583333
           5             20.100000  2.000000
           6             15.433333  1.000000
           8             15.400000  1.000000
80         3             12.500000  3.000000
           4             17.144000  2.200000
           5             19.900000  2.000000
           6             15.050000  2.000000
81         4             16.466667  2.095238
           6             15.442857  1.714286
           8             19.000000  1.000000
82         4             16.703571  1.714286
           6             16.033333  1.000000

In [ ]:
df.groupby(['model_year', 'cylinders']).mean(numeric_only=True).index # calculating the mean of numerical columns grouped by 'model_year' and 'cylinders'

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

task for activity based

In [4]:
import pandas as pd
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\mpg.csv") # reading a CSV file into a DataFrame
df.head() # viewing the first few rows of the DataFrame|

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [5]:
df.info() # getting information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [7]:
df.groupby('cylinders').mean(numeric_only = True)  # grouping the DataFrame by 'cylinders' column

,mpg,displacement,weight,acceleration,model_year,origin
cylinders,,,,,,
3,20.550000,72.500000,2398.500000,13.250000,75.500000,3.000000
4,29.286765,109.796569,2308.127451,16.601471,77.073529,1.985294
5,27.366667,145.000000,3103.333333,18.633333,79.000000,2.000000
6,19.985714,218.142857,3198.226190,16.263095,75.928571,1.190476
8,14.963107,345.009709,4114.718447,12.955340,73.902913,1.000000

In [8]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [9]:
df.groupby('origin').value_counts() # counting occurrences of each unique value in the 'origin' column after grouping by 'origin'

origin  mpg   cylinders  displacement  horsepower  weight  acceleration  model_year  name
1       9.0   8          304.0         193         4732    18.5          70          hi 1200d               1
        10.0  8          307.0         200         4376    15.0          70          chevy c20              1
                         360.0         215         4615    14.0          70          ford f250              1
        11.0  8          318.0         210         4382    13.5          70          dodge d200             1
                         350.0         180         3664    11.0          73          oldsmobile omega       1
                                                                                                           ..
3       39.1  4          79.0          58          1755    16.9          81          toyota starlet         1
        39.4  4          85.0          70          2070    18.6          78          datsun b210 gx         1
        40.8  4          85.0          65          2110    19.2          80          datsun 210             1
        44.6  4          91.0          67          1850    13.8          80          honda civic 1500 gl    1
        46.6  4          86.0          65          2110    17.9          80          mazda glc              1
Name: count, Length: 398, dtype: int64

In [10]:
df.groupby('origin').mean(numeric_only=True) # calculating the mean of numerical columns grouped by 'origin'

,mpg,cylinders,displacement,weight,acceleration,model_year
origin,,,,,,
1,20.083534,6.248996,245.901606,3361.931727,15.033735,75.610442
2,27.891429,4.157143,109.142857,2423.300000,16.787143,75.814286
3,30.450633,4.101266,102.708861,2221.227848,16.172152,77.443038

In [12]:
df.groupby('origin').sum(numeric_only=True) # calculating the mean of numerical columns grouped by 'origin'

           mpg  cylinders  displacement  weight  acceleration  model_year
origin
1       5000.8       1556       61229.5  837121        3743.4       18827
2       1952.4        291        7640.0  169631        1175.1        5307
3       2405.6        324        8114.0  175477        1277.6        6118

In [15]:
year_cyl = df.groupby(['model_year','cylinders']).mean(numeric_only=True) # grouping the DataFrame by 'model_year' and 'cylinders' and calculating the mean of numerical columns
year_cyl

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [18]:
year_cyl.index.levels # accessing the levels of the MultiIndex in the year_cyl DataFrame

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [19]:
year_cyl.loc[70] # accessing data for the year 70 in the year_cyl DataFrame

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [20]:
year_cyl.loc[ (70,4) ] # accessing the row for model year 70 and 4 cylinders

mpg               25.285714
displacement     107.000000
weight          2292.571429
acceleration      16.000000
origin             2.285714
Name: (70, 4), dtype: float64

In [ ]:
year_cyl.loc[[70,82]] # accessing data for model years 70 and 82 in the year_cyl DataFrame

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
82         4          1.714286
           6          1.000000

#concatenation

In [ ]:
import pandas as pd # importing the pandas library

In [ ]:
one = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']}) # creating the first DataFrame
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
two = pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']}) # creating the second DataFrame
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [5]:
pd.concat([one, two], axis = 1) # concatenating two DataFrames side by side (column-wise)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

combining table: inner, outer, left & right

In [ ]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']}) # creating two DataFrames for registrations and logins

In [ ]:
registrations # viewing the registrations DataFrame

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [ ]:
logins # viewing the logins DataFrame

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [6]:
pd.merge(registrations, logins, how='inner', on='name') # performing an inner join on the 'name' column

   reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4

In [ ]:
pd.merge(registrations, logins, how = 'outer', on = 'name') # performing an outer join on the 'name' column

   reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0     Bobo     4.0
2     3.0   Claire     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0

In [13]:
result = pd.merge(registrations, logins, how = 'inner', left_on='reg_id', right_on='log_id')   # merging two DataFrames using different columns as keys for the left and right DataFrames
result

   reg_id  name_x  log_id   name_y
0       1  Andrew       1   Xavier
1       2    Bobo       2   Andrew
2       3  Claire       3  Yolanda
3       4   David       4     Bobo

In [ ]:
result.drop('name_x', axis = 1) # dropping the 'name_x' column from the result DataFrame

   reg_id  log_id   name_y
0       1       1   Xavier
1       2       2   Andrew
2       3       3  Yolanda
3       4       4     Bobo

#text method

In [15]:
import pandas as pd
import numpy as np

In [23]:
email = 'rahul@email.com'
email.split('@') # splitting the email address at the '@' character

['rahul', 'email.com']

In [25]:
email.isdigit() # checking if the string consists only of digits

False

In [28]:
name = pd.Series(['rahul','alice','bob','5'])
name

0    rahul
1    alice
2      bob
3        5
dtype: object

In [30]:
'5'.isdigit() # checking which names in the Series consist only of digits

True

In [20]:
name.str.upper() # converting all names in the Series to uppercase

0    RAHUL
1    ALICE
2      BOB
3        5
dtype: object

In [31]:
name.str.isdigit() # checking which names in the Series consist only of digits

0    False
1    False
2    False
3     True
dtype: bool

In [38]:
tech_comp = ['Google, Microsoft, Apple, Amazon', 'Facebook, Tesla, Netflix, Adobe']

In [35]:
result = pd.Series(tech_comp).str.split(', ') # splitting the company names in the Series at the ', ' character
result

0    [Google, Microsoft, Apple, Amazon]
1     [Facebook, Tesla, Netflix, Adobe]
dtype: object

In [37]:
result[0][0]

'Google'

In [42]:
result1 = pd.Series(tech_comp) 
result1

0    Google, Microsoft, Apple, Amazon
1     Facebook, Tesla, Netflix, Adobe
dtype: object

In [44]:
tickers = result1.str.split(', ', expand=True) # extracting the first company name from each entry in the Series
tickers

          0          1        2       3
0    Google  Microsoft    Apple  Amazon
1  Facebook      Tesla  Netflix   Adobe

In [53]:
#messy name
messy_name = pd.Series(['  rahul  ','  Alice ',' Bo;b  ','   Charlie  '])
messy_name.str.strip() # removing leading and trailing whitespace from each name in the Series

0      rahul
1      Alice
2       Bo;b
3    Charlie
dtype: object

In [51]:
messy_name.str.replace(';',"").str.strip().str.capitalize() # removing semicolons from each name in the Series, stripping whitespace, and capitalizing the first letter

0      Rahul
1      Alice
2        Bob
3    Charlie
dtype: object

In [52]:
def clean_name(name):
    name = name.replace(';',"") # removing semicolons
    name = name.strip() # stripping leading and trailing whitespace
    name = name.capitalize() # capitalizing the first letter
    return name

In [54]:
messy_name.apply(clean_name)

0      Rahul
1      Alice
2        Bob
3    Charlie
dtype: object

#timemethod for date and time method

In [2]:
import pandas as pd
import numpy as np

from datetime import datetime

In [3]:
my_year = 2024
my_month = 6
my_day = 15
my_hour = 13
my_minute = 30
my_second = 15

In [10]:
my_date = datetime(my_year,my_month,my_day) # creating a datetime object with specified year, month, and day
my_date

datetime.datetime(2024, 6, 15, 0, 0)

In [6]:
my_datetime = datetime(my_year,my_month,my_day,my_hour,my_minute,my_second) # creating a datetime object with specified year, month, day, hour, minute, and second
my_datetime

datetime.datetime(2024, 6, 15, 13, 30, 15)

In [11]:
my_date.year # getting the year from the datetime object

2024

In [8]:
my_datetime.hour # getting the hour from the datetime object

13

In [12]:
my_date.hour # trying to get the hour from a date object (will raise an error)

0

In [ ]:
#to deal pandas series dataset frame hence this is the implementation to check and verify the datetime object features

In [ ]:
myser = pd.Series(['Nov 3,1999','2000-01-01',None]) # Creating a pandas Series with date strings and a None value
myser

0    Nov 3,1999
1    2000-01-01
2          None
dtype: object

In [ ]:
myser[0].year # getting the year from the first element of the Series

AttributeError: 'str' object has no attribute 'year'

In [ ]:
pd.to_datetime(myser) # Convert the series to datetime objects

C:\Users\admin\AppData\Local\Temp\ipykernel_8780\2184848876.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(myser)

0   1999-11-03
1   2000-01-01
2          NaT
dtype: datetime64[ns]

In [ ]:
timeseries = pd.to_datetime(myser) # Convert the series to datetime objects
timeseries

C:\Users\admin\AppData\Local\Temp\ipykernel_8780\1301300605.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  timeseries = pd.to_datetime(myser)

0   1999-11-03
1   2000-01-01
2          NaT
dtype: datetime64[ns]

In [24]:
timeseries[0].year # Access the first element of the timeseries

1999

In [25]:
#euro date

obvi_euro_date = '31-12-2000'

In [28]:
pd.to_datetime(obvi_euro_date) # Convert the series to datetime objects

C:\Users\admin\AppData\Local\Temp\ipykernel_8780\3295874962.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(obvi_euro_date) # Convert the series to datetime objects

Timestamp('2000-12-31 00:00:00')

In [29]:
euro_date = '10-12-2000'

In [32]:
pd.to_datetime(euro_date, dayfirst = True)  # machine interprets this as 12th October 2000

Timestamp('2000-12-10 00:00:00')

In [33]:
style_date = '10--Dec--2000'
pd.to_datetime(style_date, format='%d--%b--%Y') # Convert the series to datetime objects

Timestamp('2000-12-10 00:00:00')

In [34]:
custom_date = '20th of Dec 2000'
pd.to_datetime(custom_date) # Convert the series to datetime objects

Timestamp('2000-12-20 00:00:00')

In [66]:
#read csv file data to work on timstamp series
sales = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\RetailSales_BeerWineLiquor.csv", parse_dates=['DATE']) # reading a CSV file into a DataFrame
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [ ]:
sales['DATE'] # Convert the series to datetime objects

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: object

In [ ]:
sales['DATE'] =pd.to_datetime(sales['DATE']) # Convert the series to datetime objects
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [ ]:
sales['DATE'][0].year # accessing the year of the first date in the 'DATE' column

1992

In [ ]:
sales['DATE'][0].month # accessing the month of the first date in the 'DATE' column

1

In [50]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\RetailSales_BeerWineLiquor.csv",parse_dates=['DATE']) # reading a CSV file into a DataFrame
df

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [51]:
df['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [52]:
df.set_index('DATE') # setting the 'DATE' column as the index of the DataFrame

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [62]:
sales.set_index('DATE') # setting the 'DATE' column as the index of the DataFrame

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [71]:
#willing to perform group by year then calculate the mean of other sale # setting the 'DATE' column as the index of the DataFrame
sales.set_index('DATE').resample('A').mean() # resampling the DataFrame by year and calculating the mean of other columns

C:\Users\admin\AppData\Local\Temp\ipykernel_8780\1897953603.py:2: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  sales.set_index('DATE').resample('A').mean() # resampling the DataFrame by year and calculating the mean of other columns

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

In [72]:
sales['DATE'].dt.year # accessing the year of the dates in the 'DATE' column

0      1992
1      1992
2      1992
3      1992
4      1992
       ...
335    2019
336    2020
337    2020
338    2020
339    2020
Name: DATE, Length: 340, dtype: int32

In [73]:
sales['DATE'].dt.month # accessing the month of the dates in the 'DATE' column

0       1
1       2
2       3
3       4
4       5
       ..
335    12
336     1
337     2
338     3
339     4
Name: DATE, Length: 340, dtype: int32

#DATA Input Output CSV File

In [74]:
import pandas as pd

In [ ]:
pwd # checking current working directory

'c:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\notebooks'

In [ ]:
ls # checking current working directory

 Volume in drive C has no label.
 Volume Serial Number is 5492-6106

 Directory of c:\Users\admin\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\Desktop\ml-algorithms-practice\notebooks

23-11-2025  05:14    <DIR>          .
21-10-2025  12:34    <DIR>          ..
21-10-2025  12:34                 2 .gitkeep
21-10-2025  18:27            65,234 09-Inputs-and-Outputs.ipynb
21-10-2025  18:27           101,081 10-Pivot-Tables.ipynb
21-10-2025  18:27            47,135 11-Pandas-Project-Exercise .ipynb
21-10-2025  18:27            52,576 12-Pandas-Project-Exercise-Solution.ipynb
17-11-2025  08:07            51,889 numpy.ipynb
12-11-2025  16:47            23,129 numpy_exercise.ipynb
23-11-2025  05:34           556,961 pandas.ipynb
15-11-2025  07:19            32,190 pandas_revision.ipynb
13-11-2025  08:04            24,286 revision(pandas+numpy).ipynb
              10 File(s)        954,483 bytes
               2 Dir(s)  150,145,495,040 bytes free

In [ ]:
import os # importing the os module

In [79]:
os.getcwd() # getting the current working directory

'c:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\notebooks'

reading and creating the csv file

In [ ]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\example.csv", index_col=0) # reading a CSV file into a DataFrame and setting 0 as the index column
df

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [86]:
#now after performing the changes just the create the cvs and save the file back to disk
df.to_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\example_modified.csv", index=False) # saving the modified DataFrame back to a CSV file

In [87]:
df01 = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\example_modified.csv") # reading the modified CSV file back into a DataFrame
df01

    b   c   d
0   1   2   3
1   5   6   7
2   9  10  11
3  13  14  15

reading and creating HTML table

In [121]:
import pandas as pd
import numpy as np
import requests

In [122]:
url = "https://en.wikipedia.org/wiki/World_population" # URL of the Wikipedia page containing world population data

In [123]:
# Fetch the page manually
response = requests.get(url, headers=headers)
response.raise_for_status()

# Read tables from the HTML text
tables = pd.read_html(response.text)

len(tables) # checking the number of tables and viewing the first few rows of the first table

C:\Users\admin\AppData\Local\Temp\ipykernel_8780\113930913.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

26

In [124]:
len(tables), tables[0].head() # checking the number of tables and viewing the first few rows of the first table

(26,
       Population     1     2     3     4     5     6     7     8     9    10
 0           Year  1804  1927  1960  1974  1987  1999  2011  2022  2037  2057
 1  Years elapsed     –   123    33    14    13    12    12    11    15    20)

In [125]:
tables[0] # viewing the first table from the list of tables

      Population     1     2     3     4     5     6     7     8     9    10
0           Year  1804  1927  1960  1974  1987  1999  2011  2022  2037  2057
1  Years elapsed     –   123    33    14    13    12    12    11    15    20

In [126]:
tables[2] # viewing the third table on the page

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,439,090,595 – India","13,515,000 – Tokyo Metropolis (37,400,000 – Gr..."
1,Africa,44.4,1340,"0,211,401,000 – Nigeria","09,500,000 – Cairo (20,076,000 – Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 – Russia, approx. 110 million in...","13,200,000 – Moscow (20,004,000 – Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 – Brazil","12,252,000 – São Paulo City (21,650,000 – São ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 – United States","08,804,000 – New York City (23,582,649 – New Y..."
5,Oceania,5,42,"0,025,917,000 – Australia","05,367,000 – Sydney"
6,Antarctica,~0,0.004[89],N/A[note 2],"00,001,258 – McMurdo Station"

In [127]:
tables[2].columns # viewing the column names of the third table

Index(['Region', 'Density (inhabitants/km2)', 'Population (millions)',
       'Most populous country', 'Most populous city (metropolitan area)'],
      dtype='object')

In [128]:
tables[1].columns # viewing the column names of the second table

Index(['Region', '2022 (percent)', '2030 (percent)', '2050 (percent)'], dtype='object')

In [129]:
tables[5] # viewing the sixth table on the page

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                  Israel     9402617       21937                429
9    10                   India  1389637446     3287263                423

In [135]:
world_pop = tables[5] # selecting the sixth table as the world population DataFrame
world_pop.head() # viewing the first few rows of the world population DataFrame

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520

In [136]:
world_pop = world_pop.drop('Rank', axis = 1) # dropping the 'Rank' column from the world population DataFrame
world_pop

                  Country  Population  Area (km2)  Density (pop/km2)
0               Singapore     5921231         719               8235
1              Bangladesh   165650475      148460               1116
2  Palestine[note 3][102]     5223000        6025                867
3          Taiwan[note 4]    23580712       35980                655
4             South Korea    51844834       99720                520
5                 Lebanon     5296814       10400                509
6                  Rwanda    13173730       26338                500
7                 Burundi    12696478       27830                456
8                  Israel     9402617       21937                429
9                   India  1389637446     3287263                423

In [138]:
world_pop.columns = ['Country','Population','Area','Density'] # renaming the columns of the world population DataFrame
world_pop

                  Country  Population     Area  Density
0               Singapore     5921231      719     8235
1              Bangladesh   165650475   148460     1116
2  Palestine[note 3][102]     5223000     6025      867
3          Taiwan[note 4]    23580712    35980      655
4             South Korea    51844834    99720      520
5                 Lebanon     5296814    10400      509
6                  Rwanda    13173730    26338      500
7                 Burundi    12696478    27830      456
8                  Israel     9402617    21937      429
9                   India  1389637446  3287263      423

In [142]:
world_pop.to_html('C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\world_topten_population.html') # saving the top ten countries by population to an HTML file

#Data Input output Excel File

In [151]:
%pip install openpyxl
%pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [152]:
import pandas as pd
import openpyxl
import xlrd

In [ ]:
df = pd.read_excel('C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\my_excel_file.xlsx', sheet_name='First_Sheet') # reading an Excel file into a DataFrame
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [154]:
wb = pd.ExcelFile('C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\my_excel_file.xlsx') # loading the Excel file
wb.sheet_names # viewing the sheet names in the Excel file

['First_Sheet']

#Data input output - SQL

In [156]:
%pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from sqlalchemy) (4.15.0)
Using cached sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl (2.1 MB)
Using cached greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.2.4 sqlalchemy-2.0.44
Note: you may need to restart the kernel to use updated packages.

In [160]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
import numpy as np

In [159]:
temp_eng = create_engine('sqlite:///:memory:') # creating an in-memory SQLite database engine

In [161]:
df = pd.DataFrame(np.random.randint(0,100,size=(4,4)), columns=list('ABCD'))
df

    A   B   C   D
0  71  43  33  85
1  30  46  66  38
2  83  14  38  77
3  48  50  27   5

In [167]:
df.to_sql('my_table', temp_eng) # writing the DataFrame to a SQL table named 'my_table'

4

In [168]:
df.to_sql('my_table', temp_eng) # writing the DataFrame to a SQL table named 'my_table'

ValueError: Table 'my_table' already exists.

In [171]:
new_df = pd.read_sql('my_table', temp_eng) # reading the SQL table 'my_table' into a new DataFrame
new_df

   index   A   B   C   D
0      0  71  43  33  85
1      1  30  46  66  38
2      2  83  14  38  77
3      3  48  50  27   5

In [174]:
result = pd.read_sql_query('SELECT A,C FROM my_table', temp_eng) # executing a SQL query to select columns A and C from the 'my_table'
result

    A   C
0  71  33
1  30  66
2  83  38
3  48  27

#pandas pivot tables

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\Sales_Funnel_CRM.csv")
df

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won
5,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Analytics,300,2800000,Under Review
6,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Prediction,150,700000,Presented
7,1216870,Microsoft,Will Grates,Edward Thorp,Tracking,300,350000,Under Review
8,2200450,Walmart,Will Grates,Edward Thorp,Analytics,150,2450000,Lost
9,405886,Apple,Cindy Phoner,Claude Shannon,Analytics,300,4550000,Won
10,470248,Exxon Mobile,Cindy Phoner,Claude Shannon,Analytics,150,2100000,Presented
11,698032,ATT,Cindy Phoner,Claude Shannon,Tracking,150,350000,Under Review
12,698032,ATT,Cindy Phoner,Claude Shannon,Prediction,150,700000,Presented
13,902797,CVS Health,Emma Gordian,Claude Shannon,Tracking,450,490000,Won
14,2046943,Salesforce,Emma Gordian,Claude Shannon,Analytics,750,7000000,Won
15,2169499,Cisco,Emma Gordian,Claude Shannon,Analytics,300,4550000,Lost
16,2169499,Cisco,Emma Gordian,Claude Shannon,GPS Positioning,300,350000,Presented

In [178]:
help(pd.pivot)

Help on function pivot in module pandas.core.reshape.pivot:

pivot(
    data: 'DataFrame',
    *,
    columns: 'IndexLabel',
    index: 'IndexLabel | lib.NoDefault' = <no_default>,
    values: 'IndexLabel | lib.NoDefault' = <no_default>
) -> 'DataFrame'
    Return reshaped DataFrame organized by given index / column values.

    Reshape data (produce a "pivot" table) based on column values. Uses
    unique values from specified `index` / `columns` to form axes of the
    resulting DataFrame. This function does not support data
    aggregation, multiple values will result in a MultiIndex in the
    columns. See the :ref:`User Guide <reshaping>` for more on reshaping.

    Parameters
    ----------
    data : DataFrame
    columns : str or object or a list of str
        Column to use to make new frame's columns.
    index : str or object or a list of str, optional
        Column to use to make new frame's index. If not given, uses existing index.
    values : str, object or a list of the previous, optional
        Column(s) to use for populating new frame's values. If not
        specified, all remaining columns will be used and the result will
        have hierarchically indexed columns.

    Returns
    -------
    DataFrame
        Returns reshaped DataFrame.

    Raises
    ------
    ValueError:
        When there are any `index`, `columns` combinations with multiple
        values. `DataFrame.pivot_table` when you need to aggregate.

    See Also
    --------
    DataFrame.pivot_table : Generalization of pivot that can handle
        duplicate values for one index/column pair.
    DataFrame.unstack : Pivot based on the index values instead of a
        column.
    wide_to_long : Wide panel to long format. Less flexible but more
        user-friendly than melt.

    Notes
    -----
    For finer-tuned control, see hierarchical indexing documentation along
    with the related stack/unstack methods.

    Reference :ref:`the user guide <reshaping.pivot>` for more examples.

    Examples
    --------
    >>> df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
    ...                            'two'],
    ...                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
    ...                    'baz': [1, 2, 3, 4, 5, 6],
    ...                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
    >>> df
        foo   bar  baz  zoo
    0   one   A    1    x
    1   one   B    2    y
    2   one   C    3    z
    3   two   A    4    q
    4   two   B    5    w
    5   two   C    6    t

    >>> df.pivot(index='foo', columns='bar', values='baz')
    bar  A   B   C
    foo
    one  1   2   3
    two  4   5   6

    >>> df.pivot(index='foo', columns='bar')['baz']
    bar  A   B   C
    foo
    one  1   2   3
    two  4   5   6

    >>> df.pivot(index='foo', columns='bar', values=['baz', 'zoo'])
          baz       zoo
    bar   A  B  C   A  B  C
    foo
    one   1  2  3   x  y  z
    two   4  5  6   q  w  t

    You could also assign a list of column names or a list of index names.

    >>> df = pd.DataFrame({
    ...        "lev1": [1, 1, 1, 2, 2, 2],
    ...        "lev2": [1, 1, 2, 1, 1, 2],
    ...        "lev3": [1, 2, 1, 2, 1, 2],
    ...        "lev4": [1, 2, 3, 4, 5, 6],
    ...        "values": [0, 1, 2, 3, 4, 5]})
    >>> df
        lev1 lev2 lev3 lev4 values
    0   1    1    1    1    0
    1   1    1    2    2    1
    2   1    2    1    3    2
    3   2    1    2    4    3
    4   2    1    1    5    4
    5   2    2    2    6    5

    >>> df.pivot(index="lev1", columns=["lev2", "lev3"], values="values")
    lev2    1         2
    lev3    1    2    1    2
    lev1
    1     0.0  1.0  2.0  NaN
    2     4.0  3.0  NaN  5.0

    >>> df.pivot(index=["lev1", "lev2"], columns=["lev3"], values="values")
          lev3    1    2
    lev1  lev2
       1     1  0.0  1.0
             2  2.0  NaN
       2     1  4.0  3.0
             2  NaN  5.0

    A ValueError is raised if there are any duplicates.

    >>> df = pd.DataFrame({"foo": ['one', 'one', 'two', 'two'],
    ...                    "bar": ['A', 'A', 'B', 'C'],
    ...                    "baz": [1, 2, 3, 4]})
    >>> df
       foo bar  baz
    0  one   A    1
    1  one   A    2
    2  two   B    3
    3  two   C    4

    Notice that the first two rows are the same for our `index`
    and `columns` arguments.

    >>> df.pivot(index='foo', columns='bar', values='baz')
    Traceback (most recent call last):
       ...
    ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
licenses = df[['Company','Product','Licenses']] # selecting specific columns from the DataFrame
licenses

         Company          Product  Licenses
0         Google        Analytics       150
1         Google       Prediction       150
2         Google         Tracking       300
3           BOBO        Analytics       150
4           IKEA        Analytics       300
5     Tesla Inc.        Analytics       300
6     Tesla Inc.       Prediction       150
7      Microsoft         Tracking       300
8        Walmart        Analytics       150
9          Apple        Analytics       300
10  Exxon Mobile        Analytics       150
11           ATT         Tracking       150
12           ATT       Prediction       150
13    CVS Health         Tracking       450
14    Salesforce        Analytics       750
15         Cisco        Analytics       300
16         Cisco  GPS Positioning       300

In [187]:
result = pd.pivot(data = licenses, index = 'Company', columns='Product', values='Licenses') # creating a pivot table with 'Company' as index, 'Product' as columns, and 'Licenses' as values
result

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [190]:
df01 = pd.pivot_table(result, index = 'Company', aggfunc = 'sum') # creating a pivot table with 'Company' as index and summing all numerical columns
df01

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              0.0       150.0     300.0
ATT                 0.0              0.0       150.0     150.0
Apple             300.0              0.0         0.0       0.0
BOBO              150.0              0.0         0.0       0.0
CVS Health          0.0              0.0         0.0     450.0
Cisco             300.0            300.0         0.0       0.0
Exxon Mobile      150.0              0.0         0.0       0.0
IKEA              300.0              0.0         0.0       0.0
Microsoft           0.0              0.0         0.0     300.0
Salesforce        750.0              0.0         0.0       0.0
Tesla Inc.        300.0              0.0       150.0       0.0
Walmart           150.0              0.0         0.0       0.0

In [193]:
df.groupby('Company').sum() # grouping the DataFrame by 'Company' and summing all numerical columns

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              0.0       150.0     300.0
ATT                 0.0              0.0       150.0     150.0
Apple             300.0              0.0         0.0       0.0
BOBO              150.0              0.0         0.0       0.0
CVS Health          0.0              0.0         0.0     450.0
Cisco             300.0            300.0         0.0       0.0
Exxon Mobile      150.0              0.0         0.0       0.0
IKEA              300.0              0.0         0.0       0.0
Microsoft           0.0              0.0         0.0     300.0
Salesforce        750.0              0.0         0.0       0.0
Tesla Inc.        300.0              0.0       150.0       0.0
Walmart           150.0              0.0         0.0       0.0

In [202]:
df01 = pd.pivot_table(licenses, index='Company', values='Licenses', aggfunc='sum')
df01

              Licenses
Company
 Google            600
ATT                300
Apple              300
BOBO               150
CVS Health         450
Cisco              600
Exxon Mobile       150
IKEA               300
Microsoft          300
Salesforce         750
Tesla Inc.         450
Walmart            150

In [4]:
# Can add on multiple columns
pd.pivot_table(df,index=["Account Manager","Contact"],values=["Sale Price","Licenses"],columns=["Product"],
               aggfunc=[np.sum],fill_value=0)

C:\Users\admin\AppData\Local\Temp\ipykernel_20340\2237635367.py:2: FutureWarning: The provided callable <function sum at 0x0000021FC5BE4AE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=["Account Manager","Contact"],values=["Sale Price","Licenses"],columns=["Product"],

                                   sum                                      \
                              Licenses
Product                      Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner       450               0        150      150
                Emma Gordian      1050             300          0      450
Edward Thorp    Elon Tusk          600               0        150        0
                Larry Pager        300               0        150      300
                Will Grates        150               0          0      300


                             Sale Price
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    6650000               0     700000   350000
                Emma Gordian   11550000          350000          0   490000
Edward Thorp    Elon Tusk       7350000               0     700000        0
                Larry Pager     4550000               0     700000   350000
                Will Grates     2450000               0          0   350000

In [5]:
# Can add on multiple columns
pd.pivot_table(df,index=["Account Manager","Contact","Product"],values=["Sale Price","Licenses"],
               aggfunc=[np.sum],fill_value=0)

C:\Users\admin\AppData\Local\Temp\ipykernel_20340\1318361889.py:2: FutureWarning: The provided callable <function sum at 0x0000021FC5BE4AE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=["Account Manager","Contact","Product"],values=["Sale Price","Licenses"],

                                                  sum
                                             Licenses Sale Price
Account Manager Contact      Product
Claude Shannon  Cindy Phoner Analytics            450    6650000
                             Prediction           150     700000
                             Tracking             150     350000
                Emma Gordian Analytics           1050   11550000
                             GPS Positioning      300     350000
                             Tracking             450     490000
Edward Thorp    Elon Tusk    Analytics            600    7350000
                             Prediction           150     700000
                Larry Pager  Analytics            300    4550000
                             Prediction           150     700000
                             Tracking             300     350000
                Will Grates  Analytics            150    2450000
                             Tracking             300     350000

In [6]:
# get Final "ALL" with margins = True
# Can add on multiple columns
pd.pivot_table(df,index=["Account Manager","Contact","Product"],values=["Sale Price","Licenses"],
               aggfunc=[np.sum],fill_value=0,margins=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_20340\1446929768.py:3: FutureWarning: The provided callable <function sum at 0x0000021FC5BE4AE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=["Account Manager","Contact","Product"],values=["Sale Price","Licenses"],

                                                  sum
                                             Licenses Sale Price
Account Manager Contact      Product
Claude Shannon  Cindy Phoner Analytics            450    6650000
                             Prediction           150     700000
                             Tracking             150     350000
                Emma Gordian Analytics           1050   11550000
                             GPS Positioning      300     350000
                             Tracking             450     490000
Edward Thorp    Elon Tusk    Analytics            600    7350000
                             Prediction           150     700000
                Larry Pager  Analytics            300    4550000
                             Prediction           150     700000
                             Tracking             300     350000
                Will Grates  Analytics            150    2450000
                             Tracking             300     350000
All                                              4500   36540000

In [7]:
pd.pivot_table(df,index=["Account Manager","Status"],values=["Sale Price"],
               aggfunc=[np.sum],fill_value=0,margins=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_20340\1617676898.py:1: FutureWarning: The provided callable <function sum at 0x0000021FC5BE4AE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=["Account Manager","Status"],values=["Sale Price"],

                                    sum
                             Sale Price
Account Manager Status
Claude Shannon  Lost            4550000
                Presented       3150000
                Under Review     350000
                Won            12040000
Edward Thorp    Lost            4900000
                Presented       3500000
                Under Review    3500000
                Won             4550000
All                            36540000