#Installing and Importing Pandas

In [1]:
import pandas as pd

Creating DataFrames

In [4]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 30, 35]} #Create DataFrame using dictionary:

In [3]:
df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Creating a Series

In [ ]:
import pandas as pd
age_series = pd.Series([25, 30, 35], index=['Alice', 'Bob', 'Charlie'])
print(age_series)

Alice      25
Bob        30
Charlie    35
dtype: int64

Reading CSV Files

In [7]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\Housing.csv")
print(df)

     area     price
0    7420  13300000
1    8960  12250000
2    9960  12250000
3    7500  12215000
4    7420  11410000
..    ...       ...
540  3000   1820000
541  2400   1767150
542  3620   1750000
543  2910   1750000
544  3850   1750000

[545 rows x 2 columns]

Understanding and Analyzing the Data Frame

In [2]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [24, 27, 22, 32, 29],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']}

df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29      Phoenix

In [13]:
print("First 5 rows of the DataFrame:")
print(df.head(5))

print("\nLast 5 rows of the DataFrame:")
print(df.tail(5))   

print("\nDataFrame summary using info():")
df.info()

First 5 rows of the DataFrame:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29      Phoenix

Last 5 rows of the DataFrame:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29      Phoenix

DataFrame summary using info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

Indexing in Pandas

In [24]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 30, 35]}
df = pd.DataFrame(data)

# Select a single column
df_index = df['Age']
print(df_index)

# Select multiple columns
df_multiple_index = df[['Name', 'Age']]
print("\nmultiple index: ",df_multiple_index) 

#select rows by position
row_0 = df.iloc[0]
print("\nrow 0: ",row_0)

# select by iloc for multiple rows
rows_0_1 = df.loc[0:2] 
print("\nrows 0 to 2: ",rows_0_1)

0    25
1    30
2    35
Name: Age, dtype: int64

multiple index:        Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

row 0:  Name    Alice
Age        25
Name: 0, dtype: object

rows 0 to 2:        Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Selecting and Filtering Data - Techniques to Filter Based on Conditions

In [27]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 30, 35]}
df = pd.DataFrame(data)
# Filter rows where Age is greater than 28
filtered_df = df[df['Age'] > 28]
print(filtered_df)

      Name  Age
1      Bob   30
2  Charlie   35

#Dealing with Rows and Columns in Pandas DataFram

Adding a New Column to DataFrame

In [29]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]})
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [30]:
df['Salary'] = [50000, 60000, 70000]
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

renaming the column of the dataframe

In [ ]:
df.rename(columns = {'Salary': 'Income'}, inplace = True)
df

      Name  Age  Income
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [32]:
df.rename(columns = {'Salary': 'Income', 'Name': 'Employee_Name', 'Age': 'Employee_Age'}, inplace = True)
df

  Employee_Name  Employee_Age  Income
0         Alice            25   50000
1           Bob            30   60000
2       Charlie            35   70000

 Reindexing Data with Pandas

In [33]:
data = {'A': [10, 20, 30], 'B': [40, 50, 60]}
df = pd.DataFrame(data)

In [41]:
# Reindex rows
new_index = [0, 1, 2, 3]
df_reindexed = df.reindex(new_index)
print("Reindexed Rows:\n", df_reindexed)

Reindexed Rows:
       A     B
0  10.0  40.0
1  20.0  50.0
2  30.0  60.0
3   NaN   NaN

Handling Missing Data in Pandas

Identifying Missing Data With Pandas using:

isnull(): Returns True where values are missing (NaN), and False where values are present.
notnull(): Returns True where ues are present, and False where they are missing.

In [60]:
import numpy as np
df = pd.DataFrame({'Col1': [1, 2, np.nan],'Col2': [3, np.nan, np.nan]})
df

   Col1  Col2
0   1.0   3.0
1   2.0   NaN
2   NaN   NaN

In [ ]:
print(df.isnull()) #Returns True where values are missing (NaN), and False where values are present.

    Col1   Col2
0  False  False
1  False   True
2   True   True

In [3]:
print(df.notnull) #Returns True where ues are present, and False where they are missing.

<bound method DataFrame.notnull of       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29      Phoenix>

Filling Missing Data

In [46]:
df = pd.DataFrame({'Col1': [1, 2, np.nan],'Col2': [3, np.nan, np.nan]})

In [47]:
df.fillna(0)

   Col1  Col2
0   1.0   3.0
1   2.0   0.0
2   0.0   0.0

Dropping Missing Data With Pandas

In [49]:
data = {'Name': ['Alice', 'Bob', None], 'Age': [25, None, 35]}
df = pd.DataFrame(data)

In [51]:
drop_value = df.dropna()
print(drop_value)

    Name   Age
0  Alice  25.0

Aggregation and Grouping With Pandas

In [53]:
import pandas as pd
data = {'Category': ['A', 'B', 'A', 'B'], 'Value': [10, 20, 30, 40]}
df = pd.DataFrame(data)
df

  Category  Value
0        A     10
1        B     20
2        A     30
3        B     40

In [54]:
# Group data by 'Category' and calculate the sum
group_data = df.groupby('Category').sum()
group_data

          Value
Category
A            40
B            60

In [56]:
# Compute the mean for each group
mean_data = df.groupby('Category').mean()
mean_data

          Value
Category
A          20.0
B          30.0

In [ ]:
# Aggregate using multiple functions
aggregate_data_mutiple  = df.groupby('Category').agg(['sum', 'mean'])
print(aggregate_data_mutiple )   #.sum(), .mean(), and .size(): Perform aggregation on the grouped data.

         Value
           sum  mean
Category
A           40  20.0
B           60  30.0

In [ ]:
#Merging and Concatenating Data in Pandas

This section covers techniques for combining multiple DataFrames or Series into a single DataFrame. These operations are essential for integrating datasets and can be performed in several ways:

1. Merging DataFrames: Combines data based on common column or index using functions like merge or join. There are 4 types of joins:

- Inner Join: Keep rows that match in both DataFrames.
- Left Join: Keep all rows from the left DataFrame and match data from the right.
- Right Join and Outer Join are similar but differ in data retention rules.

In [1]:
data = {'Name': ['Alice', 'Charlie', 'Edward', 'Grace'],
        'Years_Experience': [2, 3, 4, 6],
        'Role': ['Manager', 'Analyst', 'Developer', 'HR']}